server:
  port: 8787

spring:
  application:
    name: "qafordevs"
  datasource:
    url: jdbc:postgresql://localhost:5432/qafordevs
    username: postgres
    password: Azuzag86
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
